import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './content/**/*.{js,ts}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#000666',
        'primary-fixed': '#e0e0ff',
        'primary-fixed-dim': '#bdc2ff',
        'primary-container': '#1a237e',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#000767',
        'on-primary-fixed-variant': '#343d96',
        'on-primary-container': '#8690ee',
        'inverse-primary': '#bdc2ff',
        secondary: '#2ECC71',
        'secondary-mobile': '#006e1c',
        'secondary-fixed': '#94f990',
        'secondary-fixed-dim': '#78dc77',
        'secondary-container': '#91f78e',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#002204',
        'on-secondary-fixed-variant': '#005313',
        'on-secondary-container': '#00731e',
        tertiary: '#001944',
        'tertiary-fixed': '#d9e2ff',
        'tertiary-fixed-dim': '#b0c6ff',
        'tertiary-container': '#002c6e',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#001945',
        'on-tertiary-fixed-variant': '#00429c',
        'on-tertiary-container': '#6b95f3',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#fcfcfd',
        'surface-bright': '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#4c56af',
        'surface-container': '#f3f4f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#454652',
        'on-background': '#1a1c1c',
        background: '#f9f9f9',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        outline: '#767683',
        'outline-variant': '#c6c5d4',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
        // Mobile (stitch/mobile.html)
        mobile: '0.25rem',
        'mobile-lg': '0.5rem',
        'mobile-xl': '0.75rem',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
