export {
  CTA_URL,
  OPAQUE_HEADER_ROUTES,
  QUERY_STALE_TIME_MS,
  COLONIAS_STALE_TIME_MS,
  WHATSAPP_NUMBER,
  WHATSAPP_URL,
  CONTACT_EMAIL,
  BRAND_NAME,
  NAVBAR_HEIGHT,
} from '@/lib/solicitud/infrastructure/config/appConfig'
