export const MAX_COMPROBANTES_INGRESO = 3

export const MAX_SIZE_IMAGEN_BYTES = 15 * 1024 * 1024
export const MAX_SIZE_PDF_BYTES = 15 * 1024 * 1024

export const PDF_MAX_PAGES_DOMICILIO = 5
export const PDF_MAX_PAGES_INGRESOS = 15

export const RESOLUCION_MIN_DOMICILIO_PX = 800
export const RESOLUCION_MIN_IDENTIDAD_PX = 600
