export { capturarDispositivo, capturarRed } from './captureDevice'
export type { DispositivoSnapshot, RedSnapshot } from './captureDevice'
export { calcularFingerprint } from './captureFingerprint'
export { capturarGeolocalizacion } from './captureGeo'
export type { GeolocalizacionSnapshot } from './captureGeo'
export { buildTelemetriaPayload } from './buildTelemetriaPayload'
export type { BuildTelemetriaInput } from './buildTelemetriaPayload'
export { geolocalizacionHabilitada } from './featureFlags'
export { useTelemetriaCapture } from './useTelemetriaCapture'
export { useEdicionesTracking } from './useEdicionesTracking'
